#!/bin/bash

# Define the nameservers and hosts
nameservers=("priv.ns1.jkimhost.com" "priv.ns2.jkimhost.com" "priv.ns3.jkimhost.com" "priv.ns4.jkimhost.com" "priv.ns5.jkimhost.com" "freesg.ns.jkimhost.com" "freeuk.ns.jkimhost.com")
hosts=("124.6.181.20" "124.6.181.36" "124.6.181.12")

# Function to check each nameserver for each host
check_nameservers() {
    for ns in "${nameservers[@]}"; do
        for host in "${hosts[@]}"; do
            if dig @$ns $host +short +time=1 +retries=0 | grep -q '^[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+'; then
                echo "Success: $host resolved by $ns"
            else
                echo "Fail: $host not resolved by $ns"
            fi
        done
    done
}

# Main loop
while true; do
    check_nameservers
    sleep 5
done
